### ISSUE TITLE
Unnecessarily mandatory field for manually adding a key

### ISSUE THREAD

**Issue by einsteinsfool** [freeotp/freeotp-android#143]
When you click a key icon to add a key/entry manually all fields are required. The 2nd one should be optional. It even is optional when you edit the entry. It's also not required if you're adding an entry with QR code.

**Comment by npmccallum** [comment]
Thank you for this valuable testing. We are going to remove the manual add screen in the next version. We have, instead, created a website for creating QR codes: https://freeotp.github.io/qrcode.html

**Comment by einsteinsfool** [comment]
I see. Gtk.
Well, in that case I'd like to ask for adding a counter field to the QR generator.
I tried using it and HOTP without setting a counter won't work.

**Comment by gelavat** [comment]
I agree that the second field is not mandatory, we can just enter any text we want and it works fine, so better leave it optional than mandatory (creation fails if we don't enter any text there).

However the manual add screen seems very important to keep in my opinion, because it allows you testing the private key immediately during the backup of the key in your backups. That is really useful, so we know that we did not save a wrong backup code.
