### ISSUE TITLE
Invalid links to website

### ISSUE THREAD

**Issue by Forage** [freeotp/freeotp-android#167]
Hi,

Just a minor heads-up, but most links to your website, be it in the description for the Google Play store or in the app itself, are outdated by now.

The one in the former links to a non-existing site, the latter links to a website with an invalid certificate.

**Comment by futal** [comment]
Links in the app have been fixed by commit 1590f84da1671397842c555acb364221db40ab30. Both GitHub and Apache website are available with ssl so I suggest to further change the protocol to https.

[In the Google Play store](https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp), both the Description and the Developer's contact information still refers to FedoraHosted.

**Comment by ShapeShifter499** [comment]
Why hasn't this been fixed yet?

**Comment by adambkaplan** [comment]
Closing as the links have been fixed in code. However these changes won't be reflected in the app until v2.0.0 is released.
