### ISSUE TITLE
Remove unnecessary permissions

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#75]
**Reported by dbrgn on 14 Jun 2016 12:15 UTC**
The INTERNET and READ_EXTERNAL_STORAGE permissions seem to be unused. They should be removed.

Patch is attached. Alternatively, you can pull from my fork:

$ git remote add dbrgn https://github.com/dbrgn/freeotp
$ git pull dbrgn/master

(I know people that did not want to use FreeOTP because it used the internet permission.)

**Comment by npmccallum** [comment]
**Comment by feddy on 29 Jul 2016 15:13 UTC**
I'm also wary of the app because of these required permissions, please merge this patch.

**Comment by nagromc** [comment]
Any news about that? I'm quite concerned about such a critical security app. This flaw could lead to OTP leaks, intentionally or not.

Besides, since [android.permission.INTERNET is no longer "dangerous"](https://github.com/android/platform_frameworks_base/commit/b467330b14fcd14f21e13c4dfeff97914e45cfbb), when the user installs the app from Google Play, he doesn't even know it can access the Internet.

See also [Every App Gets Internet Access on howtogeek.com](https://www.howtogeek.com/190863/androids-app-permissions-were-just-simplified-now-theyre-much-less-secure/):

> Google has also given each app Internet access, effectively removing the Internet access permission. Oh, sure, Android developers still have to declare they want Internet access when putting together the app. But users can no longer see the Internet access permission when installing an app and current apps that don’t have Internet access can now gain Internet access with an automatic update without prompting you.

**Comment by dabura667** [comment]
+1

**Comment by npmccallum** [comment]
No. FreeOTP will not drop the internet permission because it is actually required for the icon provisioning feature.

**Comment by nagromc** [comment]
I think I need another OTP generator. Thanks anyway.

**Comment by christiandreher** [comment]
This decision should definitely be reconsidered... I, personally speaking, don't care for icons, I just want my OTPs generated. But what I definitely don't want is to risk that the app leaks crucial information. @nagromc did you find any alternatives in the meanwhile?

**Comment by nagromc** [comment]
@christiandreher I totally agree with that. I prefer better security over a good looking UI for this kind of app. I don't even know how to download icons from the Internet within the app and I don't give a damn.

I haven't taken the time to check for any alternatives at the moment but I'm still looking for it. Don't miss to drop a line if you find it. [Alternativeto.net returns one FLOSS](http://alternativeto.net/software/freeotp/?license=opensource) but it isn't as easy to install as FreeOTP since it doesn't seem to exist on the Google Play Store.

Maybe we can find there the latest release of Google Authenticator before [Google decided to close the source](https://github.com/google/google-authenticator/wiki#google-authenticator-for-android).

**Comment by nagromc** [comment]
@christiandreher I totally agree with that. I prefer better security over a good looking UI for this kind of app. I don't even know how to download icons from the Internet within the app and I don't give a damn.

I haven't taken the time to check for any alternatives at the moment but I'm still looking for it. Don't miss to drop a line if you find it. [Alternativeto.net returns one FLOSS](http://alternativeto.net/software/freeotp/?license=opensource) but it isn't as easy to install as FreeOTP since it doesn't seem to exist on the Google Play Store.

Maybe we can find there the latest release of Google Authenticator before [Google decided to close the source](https://github.com/google/google-authenticator/wiki#google-authenticator-for-android).

**Comment by hvhaugwitz** [comment]
You can try [Android Token](https://github.com/markmcavoy/androidtoken) as an alternative (available via F-Droid).

**Comment by christiandreher** [comment]
Thanks for the responses.

@nagromc I think that you're talking about `Open Authenticator`. I've also found that, but all links on alternative.to seem to be dead, so I assume that the project is dead, too...

@hvhaugwitz Thank you too, but looking at the repository I am quite concerned, because it took the maintainer about a year to close an issue to add a license file. However there's one contributor whose fork got updated from time to time in the past, but it isn't reliable as well I think.

It's a shame that Google decided to make GA proprietary. I checked it on Google Play Store, and it requires the internet permission, too, by the way.dedicated community will fork one of those projects, supporting pin locks etc, and not requiring unnecessary permissions.

**Comment by nagromc** [comment]
@christiandreher The best thing to do maybe to use [one the](https://github.com/dbrgn/freeotp/commit/11278023b62665bb70fd843fd670b34fb8dbb168) [forks](https://github.com/xftroxgpx/freeotp-android/commit/f719e247117e0a8fdf6e6890e0f247f701d72b51).

[xftroxgpx/freeotp-android](https://github.com/xftroxgpx/freeotp-android) seems to be up-to-date against the [original project](https://github.com/freeotp/freeotp-android), but will the original author (@xftroxgpx or @dbrgn) continue maintaining it?

**Comment by xftroxgpx** [comment]
Hey, to be honest I didn't even get to test it yet, just pulled in that one PR then other irl things got in the way. You're better off using other forks :)

**Comment by dbrgn** [comment]
I don't have the time to maintain a fork.

If the internet permission is used to fetch icons, how can I get the app to fetch icons?

(I'd also prefer no internet permission and no automatically fetched icons.)

**Comment by hvhaugwitz** [comment]
@christiandreher the app requires no permissions and displays the tokens correctly, for me that is sufficient

**Comment by nagromc** [comment]
@charlydelta [andOTP](https://github.com/andOTP/andOTP) worth a try. Nice [Material Design UI](https://github.com/andOTP/andOTP/blob/b610afdf93a57a0b78bd2f589f440690dc5684cb/README.md#screenshots), no funky [permission](https://github.com/andOTP/andOTP/blob/b610afdf93a57a0b78bd2f589f440690dc5684cb/app/src/main/AndroidManifest.xml#L5-L6). It is still in a beta state, but it is in an active development. Exciting! It should be stable enough to try out the features, then why not definitively switch to.

It is even possible to [migrate from FreeOTP](https://github.com/andOTP/andOTP/wiki/Migration#freeotp).
